#!/usr/bin/env python3

import tkinter as tk
from tkinter import Variable, ttk, simpledialog, messagebox
import sec_db2

class CheckDbObjects():

    def __init__(self):
        pass

    def do_it(self,conn,sql) -> bool:
        conn.exec(sql)
        row = conn.fetch()
        if int(row['CNT']) > 0:
            return True
        else:
            return False


class CreateDbObjects():

    def __init__(self):
        pass

    def do_it(sself,conn,sql):
        conn.exec(sql)


class Gui(tk.Tk):

    def __init__(self):
        super().__init__()
        self.root = self
        self.root.title('Database Security System by M. Wagner')


class View(tk.Tk):

    def __init__(self):
        super().__init__()
        self.window = self
        self.window.title('Database Security System by M. Wagner')
        self.txt_chk = ''
        self.txt_crt = ''
        self.label_font = {'size':20,'weight':'BOLD'}


# -- ------------ --
# -- Basis Tables --
# -- ------------ --
T_USER = """
create table sec.t_user (
   usr_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   usr_name  varchar(200) not null,
   usr_connect varchar(200) not null,           -- for the asigned connect user
   usr_start date not null with default '2999-12-30',
   usr_end   date not null with default '2999-12-31',
   usr_mark  char(1) not null with default 'U', -- A=Admin,C=Connect,S=Secure,U=User
   primary key (usr_id),
   period business_time(usr_start,usr_end)
) in SECDAT04K index in SECIDX04K"""
T_ROLE = """
create table sec.t_role (
   rol_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   rol_name  varchar(200),
   rol_start date not null with default '2999-12-30',
   rol_end   date not null with default '2999-12-31',
   rol_description varchar(200),
   rol_type  varchar(8) not null with default 'RBAC',
   primary key (rol_id),
   period business_time(rol_start,rol_end)
) in SECDAT04K index in SECIDX04K"""
T_SCHEMA = """
create table sec.t_schema (
   sch_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   sch_name  varchar(200),
   sch_start date not null with default '2999-12-30',
   sch_end   date not null with default '2999-12-31',
   primary key (sch_id),
   period business_time(sch_start,sch_end)
) in SECDAT04K index in SECIDX04K"""
T_TABLE = """
create table sec.t_table (
   tbl_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   tbl_schema varchar(200),
   tbl_name  varchar(200),
   tbl_start date not null with default '2999-12-30',
   tbl_end   date not null with default '2999-12-31',
   primary key (tbl_id),
   period business_time(tbl_start,tbl_end)
) in SECDAT04K index in SECIDX04K"""
T_ROUTINE = """
create table sec.t_routine (
   rou_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   rou_schema varchar(200),
   rou_name  varchar(200),
   rou_start date not null with default '2999-12-30',
   rou_end   date not null with default '2999-12-31',
   rou_specific varchar(200),
   rou_type varchar(9) not null with default 'F',
   primary key (rou_id),
   period business_time(rou_start,rou_end)
) in SECDAT04K index in SECIDX04K"""
T_SEQUENCE = """
create table sec.t_sequence (
   seq_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   seq_schema varchar(200),
   seq_name  varchar(200),
   seq_start date not null with default '2999-12-30',
   seq_end   date not null with default '2999-12-31',
   primary key (seq_id),
   period business_time(seq_start,seq_end)
) in SECDAT04K index in SECIDX04K"""

# -- --------------- --
# -- Relation Tables --
# -- --------------- --
T_USR2ROL = """
create table sec.t_usr2rol (
   u2r_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   u2r_rol_id bigint not null,
   u2r_usr_id bigint not null,
   u2r_start date not null with default '2999-12-30',
   u2r_end   date not null with default '2999-12-31',
   primary key (u2r_id),
   period business_time(u2r_start,u2r_end)
) in SECDAT04K index in SECIDX04K"""
T_SCH2ROL = """
create table sec.t_sch2rol (
   s2r_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   s2r_rol_id bigint not null,
   s2r_sch_id bigint not null,
   s2r_schadm char(1) not null with default 'N',
   s2r_schsec char(1) not null with default 'N',
   s2r_start date not null with default '2999-12-30',
   s2r_end   date not null with default '2999-12-31',
   primary key (s2r_id),
   period business_time(s2r_start,s2r_end)
) in SECDAT04K index in SECIDX04K"""
T_TBL2ROL = """
create table sec.t_tbl2rol (
   t2r_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   t2r_rol_id bigint not null,
   t2r_tbl_id bigint not null,
   t2r_ctlauth char(1) not null with default 'N',
   t2r_delauth char(1) not null with default 'N',
   t2r_insauth char(1) not null with default 'N',
   t2r_selauth char(1) not null with default 'N',
   t2r_updauth char(1) not null with default 'N',
   t2r_start date not null with default '2999-12-30',
   t2r_end   date not null with default '2999-12-31',
   primary key (t2r_id),
   period business_time(t2r_start,t2r_end)
) in SECDAT04K index in SECIDX04K"""
T_ROU2ROL = """
create table sec.t_rou2rol (
   r2r_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   r2r_rol_id bigint not null,
   r2r_rou_id bigint not null,
   r2r_start date not null with default '2999-12-30',
   r2r_end   date not null with default '2999-12-31',
   primary key (r2r_id),
   period business_time(r2r_start,r2r_end)
) in SECDAT04K index in SECIDX04K"""
T_SEQ2ROL = """
create table sec.t_seq2rol (
   s2r_id    bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cycle),
   s2r_rol_id bigint not null,
   s2r_seq_id bigint not null,
   s2r_start date not null with default '2999-12-30',
   s2r_end   date not null with default '2999-12-31',
   primary key (s2r_id),
   period business_time(s2r_start,s2r_end)
) in SECDAT04K index in SECIDX04K"""

# -- --------------- --
# -- LOG TABLE       --
# -- --------------- --
T_LOG2 = """
CREATE TABLE sec.t_log2 (
   id bigint not null generated by default as identity (start with 1 increment by 1 no maxvalue no cache),
   sys_time   timestamp(12),
   sys_sql    varchar(1000),
   sys_state  char(5)
) IN secdat04k INDEX IN secidx04k"""

# -- --------------- --
# -- INDIZES         --
# -- --------------- --
X_USER = """
create unique index sec.x_user on sec.t_user (usr_id,business_time without overlaps)"""
X_ROLE = """
create unique index sec.x_role on sec.t_role (rol_id,business_time without overlaps)"""
X_SCHEMA = """
create unique index sec.x_schema on sec.t_schema (sch_id,business_time without overlaps)"""
X_TABLE = """
create unique index sec.x_table on sec.t_table (tbl_id,business_time without overlaps)"""
X_ROUTINE = """
create unique index sec.x_routine on sec.t_routine (rou_id,business_time without overlaps)"""
X_SEQUENCE = """
create unique index sec.x_sequence on sec.t_sequence (seq_id,business_time without overlaps)"""
X_USR2ROL = """
create unique index sec.x_usr2rol on sec.t_usr2rol (u2r_id,business_time without overlaps)"""
X_SCH2ROL = """
create unique index sec.x_sch2rol on sec.t_sch2rol (s2r_id,business_time without overlaps)"""
X_TBL2ROL = """
create unique index sec.x_tbl2rol on sec.t_tbl2rol (t2r_id,business_time without overlaps)"""
X_ROU2ROL = """
create unique index sec.x_rou2rol on sec.t_rou2rol (r2r_id,business_time without overlaps)"""
X_SEQ2ROL = """
create unique index sec.x_seq2rol on sec.t_seq2rol (s2r_id,business_time without overlaps)"""
X_LOG2 = """
create unique index sec.x_log2 on sec.t_log2 (id)"""

X_ROLE_U = """
CREATE UNIQUE INDEX SEC.X_ROLE_U ON SEC.T_ROLE (ROL_NAME)"""
X_ROUTINE_U = """
CREATE UNIQUE INDEX SEC.X_ROUTINE_U ON SEC.T_ROUTINE (ROU_SCHEMA,ROU_NAME,ROU_SPECIFIC)"""
X_SCHEMA_U = """
CREATE UNIQUE INDEX SEC.X_SCHEMA_U ON SEC.T_SCHEMA (SCH_NAME)"""
X_SEQUENCE_U = """
CREATE UNIQUE INDEX SEC.X_SEQUENCE_U ON SEC.T_SEQUENCE (SEQ_SCHEMA,SEQ_NAME)"""
X_TABLE_U = """
CREATE UNIQUE INDEX SEC.X_TABLE_U ON SEC.T_TABLE (TBL_SCHEMA,TBL_NAME)"""
X_USER_U = """
CREATE UNIQUE INDEX SEC.X_USER_U ON SEC.T_USER (USR_NAME)"""
X_ROU2ROL_U = """
CREATE UNIQUE INDEX SEC.X_ROU2ROL_U ON SEC.T_ROU2ROL (R2R_ROL_ID,R2R_ROU_ID)"""
X_SCH2ROL_U = """
CREATE UNIQUE INDEX SEC.X_SCH2ROL_U ON SEC.T_SCH2ROL (S2R_ROL_ID,S2R_SCH_ID)"""
X_SEQ2ROL_U = """
CREATE UNIQUE INDEX SEC.X_SEQ2ROL_U ON SEC.T_SEQ2ROL (S2R_ROL_ID,S2R_SEQ_ID)"""
X_TBL2ROL_U = """
CREATE UNIQUE INDEX SEC.X_TBL2ROL_U ON SEC.T_TBL2ROL (T2R_ROL_ID,T2R_TBL_ID)"""
X_USR2ROL_U = """
CREATE UNIQUE INDEX SEC.X_USR2ROL_U ON SEC.T_USR2ROL (U2R_ROL_ID,U2R_USR_ID)"""

# -- ---------------- --
# -- Supporting Views --
# -- ---------------- --
# -- ** PSEUDO-SYSTEM
V_ROUTINEAUTH = """
CREATE OR REPLACE VIEW sec.v_routineauth (SCHEMA,specificname,routinetype,grantee,granteetype,procname) AS
SELECT ra.SCHEMA,ra.specificname,ra.routinetype,ra.grantee,ra.granteetype,COALESCE(pc.procname,fc.funcname)
FROM syscat.routineauth AS ra LEFT OUTER JOIN syscat.procedures AS pc ON (ra.SCHEMA,ra.specificname) = (pc.procschema,pc.specificname)
                              LEFT OUTER JOIN syscat.functions  AS fc ON (ra.SCHEMA,ra.specificname) = (fc.funcschema,fc.specificname)
WHERE ra.SCHEMA IN (SELECT rou_schema FROM sec.t_routine)
AND ra.granteetype = 'R'"""
# -- ** SIMPLIFY **
V_USR2ROL = """
CREATE OR replace VIEW sec.v_usr2rol (usr_id,usr_name,usr_start,usr_end,rol_id,rol_name,rol_start,rol_end,u2r_start,u2r_end) as
SELECT usr_id,usr_name,usr_start,usr_end,rol_id,rol_name,rol_start,rol_end,u2r_start,u2r_end
FROM sec.t_usr2rol LEFT OUTER JOIN sec.t_user ON u2r_usr_id = usr_id
                   LEFT OUTER JOIN sec.t_role ON u2r_rol_id = rol_id """
V_SCH2ROL = """
create or replace view sec.v_sch2rol (sch_id,sch_name,sch_start,sch_end,rol_id,rol_name,rol_start,rol_end,s2r_id,s2r_schadm,s2r_schsec,s2r_start,s2r_end) as
select sch_id,sch_name,sch_start,sch_end,rol_id,rol_name,rol_start,rol_end,s2r_id,s2r_schadm,s2r_schsec,s2r_start,s2r_end
from sec.t_sch2rol left outer join sec.t_schema on s2r_sch_id = sch_id
                   left outer join sec.t_role   on s2r_rol_id = rol_id"""
V_TBL2ROL = """
create or replace view sec.v_tbl2rol (tbl_id,tbl_schema,tbl_name,rol_id,rol_name,t2r_id,t2r_ctlauth,t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth,t2r_start,t2r_end) as
select tbl_id,tbl_schema,tbl_name,rol_id,rol_name,t2r_id,t2r_ctlauth,t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth,t2r_start,t2r_end
from sec.t_tbl2rol left outer join sec.t_table on t2r_tbl_id = tbl_id
                   left outer join sec.t_role  on t2r_rol_id = rol_id"""
V_ROU2ROL = """
create or replace view sec.v_rou2rol (rou_id,rou_schema,rou_name,rou_specific,rou_type,rol_id,rol_name,r2r_id,r2r_start,r2r_end) as
select rou_id,rou_schema,rou_name,rou_specific,rou_type,rol_id,rol_name,r2r_id,r2r_start,r2r_end
from sec.t_rou2rol left outer join sec.t_routine on r2r_rou_id = rou_id
                   left outer join sec.t_role    on r2r_rol_id = rol_id"""
V_SEQ2ROL = """
create or replace view sec.v_seq2rol (seq_id,seq_schema,seq_name,rol_id,rol_name,s2r_id,s2r_start,s2r_end) as
select seq_id,seq_schema,seq_name,rol_id,rol_name,s2r_id,s2r_start,s2r_end
from sec.t_seq2rol left outer join sec.t_sequence on s2r_seq_id = seq_id
                   left outer join sec.t_role     on s2r_rol_id = rol_id"""
# -- ** REVOKE **
V_REVOKE_USER = """
create or replace view sec.v_revoke_user (action,usr_name,con_usr) as
select 'REVOKE',sys.surrogateauthid,sys.trustedid
from syscat.surrogateauthids as sys left outer join sec.t_user as sec on sys.surrogateauthid = sec.usr_name
where sec.usr_name is NULL
AND sys.surrogateauthidtype = 'U'"""
V_REVOKE_ROLE = """
create or replace view sec.v_revoke_role (action,rol_name) as
select 'REVOKE',sys.rolename
from syscat.roles as sys left outer join sec.t_role as sec on sys.rolename = sec.rol_name
where sec.rol_name is NULL
AND sys.roleid >= 1000"""
V_REVOKE_ROLE_ACCESS = """
CREATE OR REPLACE VIEW sec.v_revoke_role_access (action,usr_name,rol_name) as
SELECT 'REVOKE',sys.grantee,sys.rolename
FROM syscat.roleauth as sys left outer join sec.v_usr2rol as sec on (sys.grantee,sys.rolename) = (sec.usr_name,sec.rol_name)
WHERE (sec.usr_name is null or sec.rol_name is null)
AND sys.grantortype <> 'S'"""
V_REVOKE_TABLE_ACCESS = """
CREATE OR REPLACE VIEW sec.v_revoke_table_access (tbl_schema,tbl_name,rol_name,t2r_ctlauth,t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth,
                                                 tabschema,tabname,grantee,controlauth,deleteauth,insertauth,selectauth,updateauth) AS
SELECT sec.tbl_schema,sec.tbl_name,sec.rol_name,
       sec.t2r_ctlauth,t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth,
       sys.tabschema,sys.tabname,sys.grantee,
       sys.controlauth,sys.deleteauth,sys.insertauth,sys.selectauth,sys.updateauth
FROM syscat.tabauth AS sys LEFT OUTER JOIN sec.v_tbl2rol AS sec ON
    (sys.tabschema,sys.tabname,sys.grantee,sys.CONTROLAUTH,sys.DELETEAUTH,sys.INSERTAUTH,sys.SELECTAUTH,sys.UPDATEAUTH) =
    (sec.tbl_schema,sec.tbl_name,sec.rol_name,sec.t2r_ctlauth,sec.t2r_delauth,sec.t2r_insauth,sec.t2r_selauth,sec.t2r_updauth) AND sys.granteetype = 'R'
WHERE sec.tbl_schema IS NULL
AND GRANTEETYPE = 'R'
AND sys.tabschema IN (SELECT DISTINCT tbl_schema FROM sec.t_table)"""
V_REVOKE_ROUTINE_ACCESS = """
CREATE OR replace VIEW sec.v_revoke_routine_access (rou_id,rou_schema,rou_name,rou_specific,rou_type,rol_id,rol_name,r2r_id,SCHEMA,specificname,routinetype,grantee,granteetype,procname) AS
SELECT rou_id,rou_schema,rou_name,rou_specific,rou_type,rol_id,rol_name,r2r_id,SCHEMA,specificname,routinetype,grantee,granteetype,procname
FROM sec.v_routineauth LEFT OUTER JOIN sec.v_rou2rol ON (schema,specificname,grantee) = (rou_schema,rou_specific,rol_name)
WHERE ROU_SCHEMA IS NULL"""
V_REVOKE_SEQUENCE_ACCESS = """
CREATE VIEW sec.v_revoke_sequence_access (seqschema,seqname,grantee) AS
SELECT sys.seqschema,sys.seqname,sys.grantee
FROM syscat.sequenceauth AS sys LEFT OUTER JOIN sec.v_seq2rol AS sec ON (sys.seqschema,sys.seqname,sys.grantee) = (sec.seq_schema,sec.seq_name,sec.rol_name)
WHERE sys.granteetype = 'R'
AND sec.seq_schema IS NULL"""
# -- ** GRANT **
V_GRANT_USER = """
create or replace view sec.v_grant_user (action,usr_name,con_usr) as
select 'GRANT',sec.usr_name,sec.usr_connect
from sec.t_user as sec left outer join syscat.surrogateauthids as sys on sec.usr_name = sys.surrogateauthid
where sys.surrogateauthid is NULL
AND sec.usr_id > 0"""
V_GRANT_ROLE = """
create or replace view sec.v_grant_role (action,rol_name) as
select 'GRANT',sec.rol_name
from sec.t_role as sec left outer join syscat.roles as sys on sec.rol_name = sys.rolename
where sys.rolename is NULL
AND sec.rol_id > 0"""
V_GRANT_ROLE_ACCESS = """
CREATE OR REPLACE VIEW sec.v_grant_role_access (action,usr_name,rol_name) as
SELECT 'GRANT',sec.usr_name,sec.rol_name
FROM sec.v_usr2rol as sec left outer join syscat.roleauth as sys on (sec.usr_name,sec.rol_name) = (sys.grantee,sys.rolename)
WHERE (sys.grantee is null or sys.rolename is null)"""
V_GRANT_TABLE_ACCESS = """
CREATE OR REPLACE VIEW sec.v_grant_table_access (tbl_schema,tbl_name,rol_name,t2r_ctlauth,t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth,
                                                 tabschema,tabname,grantee,controlauth,deleteauth,insertauth,selectauth,updateauth) AS
SELECT sec.tbl_schema,sec.tbl_name,sec.rol_name,
       sec.t2r_ctlauth,t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth,
       sys.tabschema,sys.tabname,sys.grantee,
       sys.controlauth,sys.deleteauth,sys.insertauth,sys.selectauth,sys.updateauth
FROM sec.v_tbl2rol AS sec LEFT OUTER JOIN syscat.tabauth AS sys ON
    (sys.tabschema,sys.tabname,sys.grantee,sys.CONTROLAUTH,sys.DELETEAUTH,sys.INSERTAUTH,sys.SELECTAUTH,sys.UPDATEAUTH) =
    (sec.tbl_schema,sec.tbl_name,sec.rol_name,sec.t2r_ctlauth,sec.t2r_delauth,sec.t2r_insauth,sec.t2r_selauth,sec.t2r_updauth) AND sys.granteetype = 'R'
WHERE sys.tabschema IS NULL"""
V_GRANT_ROUTINE_ACCESS ="""
CREATE OR replace VIEW sec.v_grant_routine_access (rou_id,rou_schema,rou_name,rou_specific,rou_type,rol_id,rol_name,r2r_id,SCHEMA,specificname,routinetype,grantee,granteetype,procname) AS
SELECT rou_id,rou_schema,rou_name,rou_specific,rou_type,rol_id,rol_name,r2r_id,SCHEMA,specificname,routinetype,grantee,granteetype,procname
FROM sec.v_rou2rol LEFT OUTER JOIN sec.v_routineauth ON (rou_schema,rou_specific,rol_name) = (schema,specificname,grantee)
WHERE SCHEMA IS NULL"""
V_GRANT_SEQUENCE_ACCESS ="""
CREATE VIEW sec.v_grant_sequence_access (seq_schema,seq_name,rol_name) AS
SELECT sec.seq_schema,sec.seq_name,sec.rol_name
FROM sec.v_seq2rol AS sec LEFT OUTER JOIN syscat.sequenceauth AS sys ON (sec.seq_schema,sec.seq_name,sec.rol_name) = (sys.seqschema,sys.seqname,sys.grantee)
WHERE sys.seqschema IS NULL"""

# -- --------------------------------------------------------------------------------
# -- SECURITY PROCEDURE
# -- --------------------------------------------------------------------------------
SECURITY2 = """
CREATE OR REPLACE PROCEDURE SEC.SECURITY2()
LANGUAGE SQL
SPECIFIC SECURITY2
MODIFIES SQL DATA
BEGIN

    DECLARE sql VARCHAR(1000);
    DECLARE SQLSTATE CHAR(5);

    -- --------- HELP -------- 
    -- SET SERVER_OUTPUT = YES
    -- -----------------------

    CALL DBMS_OUTPUT.PUT_LINE('START');
    EXECUTE IMMEDIATE 'SET CURRENT TEMPORAL BUSINESS_TIME = CURRENT DATE';
    CALL DBMS_OUTPUT.PUT_LINE('BUSINESS TIME OK');

    -- MAIN PROGRAM
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'*** BEGIN ***',0);
    CALL DBMS_OUTPUT.PUT_LINE('LOG STARTED');

    -- ** REVOKE
    -- ** ** SETSESSIONUSER -----------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* REVOKE USER *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START REVOKE USER');
    FOR v_row AS SELECT action, usr_name, con_usr FROM SEC.V_REVOKE_USER
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('REVOKE USER:' + usr_name);
    --
        IF v_row.action IS NOT NULL THEN
            SET sql = action + ' SETSESSIONUSER ON USER ' + usr_name + ' FROM USER ' + con_usr;
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** DROP ROLE ----------------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* REVOKE ROLE *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START DROP ROLE');
    FOR v_row AS SELECT rol_name FROM SEC.V_REVOKE_ROLE
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('REVOKE ROLE:' + rol_name);
    --
        IF v_row.rol_name IS NOT NULL THEN
            SET sql = 'DROP ROLE ' + rol_name;
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** ROLE ACCESS --------------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* REVOKE ROLE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START REVOKE ROLE ACCESS');
    FOR v_row AS SELECT action, rol_name, usr_name FROM SEC.V_REVOKE_ROLE_ACCESS
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('REVOKE ROLEAUTH:' + rol_name + ' FROM USER:' + usr_name);
    --
        IF v_row.action IS NOT NULL THEN
            SET sql = action + ' ROLE ' + rol_name + ' FROM USER ' + usr_name;
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** TABLE ACCESS -------------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* REVOKE TABLE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START REVOKE TABLE ACCESS');
    FOR v_row AS SELECT tabschema,tabname,grantee,controlauth,deleteauth,insertauth,selectauth,updateauth
                 FROM sec.v_revoke_table_access
    DO
    --
        IF v_row.controlauth = 'Y' THEN
            CALL DBMS_OUTPUT.PUT_LINE('REVOKE TABAUTH CTL:' + tabname + ' FROM USER:' + grantee);
            SET sql = 'REVOKE CONTROL ON TABLE '||strip(tabschema)||'.'||strip(tabname)||' FROM ROLE '||strip(grantee);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.deleteauth = 'Y' THEN
            CALL DBMS_OUTPUT.PUT_LINE('REVOKE TABAUTH DEL:' + tabname + ' FROM USER:' + grantee);
            SET sql = 'REVOKE DELETE ON TABLE '||strip(tabschema)||'.'||strip(tabname)||' FROM ROLE '||strip(grantee);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.insertauth = 'Y' THEN
            CALL DBMS_OUTPUT.PUT_LINE('REVOKE TABAUTH INS:' + tabname + ' FROM USER:' + grantee);
            SET sql = 'REVOKE INSERT ON TABLE '||strip(tabschema)||'.'||strip(tabname)||' FROM ROLE '||strip(grantee);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.selectauth = 'Y' THEN
            CALL DBMS_OUTPUT.PUT_LINE('REVOKE TABAUTH SEL:' + tabname + ' FROM USER:' + grantee);
            SET sql = 'REVOKE SELECT ON TABLE '||strip(tabschema)||'.'||strip(tabname)||' FROM ROLE '||strip(grantee);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.updateauth = 'Y' THEN
            CALL DBMS_OUTPUT.PUT_LINE('REVOKE TABAUTH UPD:' + tabname + ' FROM USER:' + grantee);
            SET sql = 'REVOKE UPDATE ON TABLE '||strip(tabschema)||'.'||strip(tabname)||' FROM ROLE '||strip(grantee);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** ROUTINE ACCESS -----------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* REVOKE ROUTINE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START REVOKE ROUTINE ACCESS');
    FOR v_row AS SELECT rou_schema,rou_specific,rou_type,rol_name
              FROM SEC.V_REVOKE_ROUTINE_ACCESS
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('REVOKE EXECUTE:' + rou_specific + ' FROM USER:' + rol_name);
    --
        SET sql = 'REVOKE EXECUTE ON '||CASE WHEN rou_type = 'P' THEN 'PROCEDURE ' ELSE 'SPECIFIC FUNCTION ' END ||
            strip(v_row.rou_schema)||'.'||
            strip(CASE WHEN rou_type = 'P' THEN rou_specific ELSE rou_specific END )||' FROM ROLE '||strip(rol_name)||' RESTRICT';
        EXECUTE IMMEDIATE sql;
        INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
    END FOR;
    -- ** ** SEQUENCE ACCESS ----------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* REVOKE SEQUENCE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START REVOKE SEQUENCE ACCESS');
    FOR v_row AS SELECT seqschema,seqname,grantee
              FROM SEC.V_REVOKE_SEQUENCE_ACCESS
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('REVOKE USE:' + seqname + ' FROM USER:' + grantee);
    --
        SET sql = 'REVOKE USAGE ON SEQUENCE '||strip(v_row.seqschema)||'.'||strip(v_row.seqname)||' FROM ROLE '||strip(grantee)||' RESTRICT';
        EXECUTE IMMEDIATE sql;
        INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
    END FOR;
    -- --------------------------------------------------------------------------------

    -- ** GRANT
    -- ** ** SETSESSIONUSER -----------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* GRANT USER *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START GRANT USER');
    FOR v_row AS SELECT action, usr_name, con_usr FROM SEC.V_GRANT_USER
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('GRANT USER:' + usr_name);
    --
        IF v_row.action IS NOT NULL THEN
            SET sql = action + ' SETSESSIONUSER ON USER ' + usr_name + ' TO USER ' + con_usr;
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** CREATE ROLE --------------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* GRANT ROLE *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START CREATE ROLE');
    FOR v_row AS SELECT rol_name FROM SEC.V_GRANT_ROLE
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('GRANT ROLE:' + rol_name);
    --
        IF v_row.rol_name IS NOT NULL THEN
            SET sql = 'CREATE ROLE ' + rol_name;
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** ROLE ACCESS --------------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* GRANT ROLE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START GRANT ROLE ACCESS');
    FOR v_row AS SELECT action, rol_name, usr_name FROM SEC.V_GRANT_ROLE_ACCESS WHERE usr_name IS NOT NULL
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('GRANT ROLEAUTH:' + rol_name + ' TO USER:' + usr_name);
    --
        IF v_row.action IS NOT NULL THEN
            SET sql = action + ' ROLE ' + rol_name + ' TO USER ' + usr_name;
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** TABLE ACCESS -------------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* GRANT TABLE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START GRANT TABLE ACCESS');
    FOR v_row AS SELECT tbl_schema,tbl_name,rol_name,t2r_ctlauth,
                        t2r_delauth,t2r_insauth,t2r_selauth,t2r_updauth
                 FROM sec.v_grant_table_access
    DO
    --
        IF v_row.t2r_ctlauth = 'Y' THEN
            SET sql = 'GRANT CONTROL ON TABLE '||strip(v_row.tbl_schema)||'.'||strip(v_row.tbl_name)||
                ' TO ROLE '||strip(rol_name);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.t2r_delauth = 'Y' THEN
            SET sql = 'GRANT DELETE ON TABLE '||strip(v_row.tbl_schema)||'.'||strip(v_row.tbl_name)||
                ' TO ROLE '||strip(rol_name);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.t2r_insauth = 'Y' THEN
            SET sql = 'GRANT INSERT ON TABLE '||strip(v_row.tbl_schema)||'.'||strip(v_row.tbl_name)||
                ' TO ROLE '||strip(rol_name);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.t2r_selauth = 'Y' THEN
            SET sql = 'GRANT SELECT ON TABLE '||strip(v_row.tbl_schema)||'.'||strip(v_row.tbl_name)||
                ' TO ROLE '||strip(rol_name);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
        IF v_row.t2r_updauth = 'Y' THEN
            SET sql = 'GRANT UPDATE ON TABLE '||strip(v_row.tbl_schema)||'.'||strip(v_row.tbl_name)||
                ' TO ROLE '||strip(rol_name);
            EXECUTE IMMEDIATE sql;
            INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
        END IF;
    END FOR;
    -- ** ** ROUTINE ACCESS -----------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* GRANT ROUTINE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START GRANT ROUTINE ACCESS');
    FOR v_row AS SELECT rou_schema,rou_name,rou_specific,rou_type,rol_name
              FROM SEC.V_GRANT_ROUTINE_ACCESS
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE:' +rou_specific + ' TO USER:'+ rol_name);
    --
        SET sql = 'GRANT EXECUTE ON '||CASE WHEN rou_type = 'P' THEN 'PROCEDURE ' ELSE 'SPECIFIC FUNCTION ' END ||
            strip(v_row.rou_schema)||'.'||
            strip(CASE WHEN rou_type = 'P' THEN rou_name ELSE rou_specific END )||' TO ROLE '||strip(rol_name);
        EXECUTE IMMEDIATE sql;
        INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
    END FOR;
    -- ** ** SEQUENCE ACCESS ----------------------------------------------------------
    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'* GRANT SEQUENCE ACCESS *',0);
    CALL DBMS_OUTPUT.PUT_LINE('START GRANT SEQUENCE ACCESS');
    FOR v_row AS SELECT seq_schema,seq_name,rol_name
              FROM SEC.V_GRANT_SEQUENCE_ACCESS
    DO
    --
        CALL DBMS_OUTPUT.PUT_LINE('GRANT USE:' + seq_name + ' T USER:' + rol_name);
    --
        SET sql = 'GRANT USAGE ON SEQUENCE '||strip(v_row.seq_schema)||'.'||strip(v_row.seq_name)||' TO ROLE '||strip(rol_name);
        EXECUTE IMMEDIATE sql;
        INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,sql,SQLSTATE);
    END FOR;
    -- --------------------------------------------------------------------------------

    INSERT INTO sec.t_log2 (sys_time,sys_sql,sys_state) VALUES (CURRENT TIMESTAMP,'*** END ***',0);

END"""


class Setup():

    def __init__(self,gui):
        self.check  = CheckDbObjects()
        self.create = CreateDbObjects()
        self.gui    = gui
        self.view_master()
        self.CHECK_TXT:dict = {1:'yes',0:'no'}
        self.CREAT_TXT:dict = {1:'no',0:'yes'}

    def view_master(self):
        self.frm = ttk.LabelFrame(self.gui,text='Setup Screen')
        self.frm.grid(row=0,column=0,padx=3,pady=3,sticky=('N','E','S','W'))
        ttk.Label(self.frm,text='Server').grid(row=0,column=0,padx=3,pady=3,sticky=('E','W'))
        ttk.Label(self.frm,text='Port').grid(row=0,column=1,padx=3,pady=3,sticky=('E','W'))
        ttk.Label(self.frm,text='Database').grid(row=0,column=2,padx=3,pady=3,sticky=('E','W'))
        self.server = ttk.Entry(self.frm)
        self.server.grid(row=1,column=0,padx=3,pady=3,sticky=('E','W'))
        self.port = ttk.Entry(self.frm)
        self.port.grid(row=1,column=1,padx=3,pady=3,sticky=('E','W'))
        self.database = ttk.Entry(self.frm)
        self.database.grid(row=1,column=2,padx=3,pady=3,sticky=('E','W'))
        #
        ttk.Label(self.frm,text='SSL-Path').grid(row=2,column=0,padx=3,pady=3,sticky=('E','W'))
        ttk.Label(self.frm,text='SSL-Key').grid(row=2,column=1,padx=3,pady=3,sticky=('E','W'))
        ttk.Label(self.frm,text='SSL-Stash').grid(row=2,column=2,padx=3,pady=3,sticky=('E','W'))
        self.ssl_pth = ttk.Entry(self.frm)
        self.ssl_pth.grid(row=3,column=0,padx=3,pady=3,sticky=('E','W'))
        self.ssl_key = ttk.Entry(self.frm)
        self.ssl_key.grid(row=3,column=1,padx=3,pady=3,sticky=('E','W'))
        self.ssl_sth = ttk.Entry(self.frm)
        self.ssl_sth.grid(row=3,column=2,padx=3,pady=3,sticky=('E','W'))
        #
        ttk.Label(self.frm,text='Connect-User').grid(row=4,column=0,padx=3,pady=3,sticky=('E','W'))
        ttk.Label(self.frm,text='Admin-User').grid(row=4,column=1,padx=3,pady=3,sticky=('E','W'))
        ttk.Label(self.frm,text='Security-User').grid(row=4,column=2,padx=3,pady=3,sticky=('E','W'))
        self.con_usr = ttk.Entry(self.frm)
        self.con_usr.grid(row=5,column=0,padx=3,pady=3,sticky=('E','W'))
        self.adm_usr = ttk.Entry(self.frm)
        self.adm_usr.grid(row=5,column=1,padx=3,pady=3,sticky=('E','W'))
        self.sec_usr = ttk.Entry(self.frm)
        self.sec_usr.grid(row=5,column=2,padx=3,pady=3,sticky=('E','W'))
        #
        self.Bt1 = tk.Button(self.frm,text='START',command=self.start_install)
        self.Bt1.grid(row=10,column=0,padx=3,pady=3,sticky=('E','W'),columnspan=3)
        self.Bt1.bind('<Button-1>',self.start_install)
        self.server.focus()

    def start_install(self,*args):
        if self.connect_instance_user():
            if self.connect_connect_user():
                self.install_routine()

    def connect_instance_user(self) -> bool:
        flag:bool = False
        tmp_usr = simpledialog.askstring(title="User",prompt="Input name for the INSTANCE user")
        tmp_pwd = simpledialog.askstring(title="Password",prompt="Input password for the INSTANCE user",show="*")
        ssl_tmp:str = ""
        if self.ssl_pth.get():
            if self.ssl_key.get():
                ssl_tmp += "SSLClientKeystoredb="+self.ssl_pth.get()+"/"+self.ssl_key.get()+";"
            if self.ssl_sth.get():
                ssl_tmp += "SSLClientKeystash="+self.ssl_pth.get()+"/"+self.ssl_sth.get()
                tmp_ssl = ";SECURITY=ssl;" + ssl_tmp
        self.ins_db2 = sec_db2.Db2()
        self.iconn = self.ins_db2.open(self.server.get(),self.port.get(),self.database.get(),ssl_tmp,tmp_usr,tmp_pwd)
        if self.iconn == True:
            sql = "SELECT SESSION_USER as SESSION_USER FROM SYSIBM.SYSDUMMY1"
            self.ins_db2.exec(sql)
            session_user = self.ins_db2.fetch()
            session_user = session_user['SESSION_USER']
            session_user = session_user.strip()
            sql = "SELECT SYSPROC.AUTH_GET_INSTANCE_AUTHID() AS INSTANCE_USER FROM SYSIBM.SYSDUMMY1"
            self.ins_db2.exec(sql)
            instance_user = self.ins_db2.fetch()
            instance_user = instance_user['INSTANCE_USER']
            if session_user == instance_user:
                flag = True
            else:
                messagebox.showerror("ERROR","This is not the Instance-User")
                self.ins_db2.close()
        return flag

    def connect_connect_user(self) -> bool:
        flag = False
        tmp_usr = self.con_usr.get()
        tmp_usr = tmp_usr.upper()
        tmp_pwd = simpledialog.askstring(title="Password",prompt="Input password for the CONNECT user",show="*")
        ssl_tmp:str = ""
        if self.ssl_pth.get():
            if self.ssl_key.get():
                ssl_tmp += f"{self.ssl_pth.get()}/{self.ssl_key.get()} "
            if self.ssl_sth.get():
                ssl_tmp += f"{self.ssl_pth.get()}/{self.ssl_sth.get()}"
        self.con_db2 = sec_db2.Db2()
        self.cconn = self.con_db2.open(self.server.get(),self.port.get(),self.database.get(),ssl_tmp,tmp_usr,tmp_pwd)
        if self.cconn == True:
            flag = True
        return flag

    # --------------------------------------------------------------------------------


    def install_routine(self):
        #view = tk.Tk()
        view = self.frm
        #scrollbar   = tk.Scrollbar(view,orient='vertical')
        #scrollbar.grid(row=0,column=5,sticky=('N','S'))
        self.container = tk.Listbox(view) # ,yscrollcommand = scrollbar.set
        self.container.grid(row=10,column=0,columnspan=3,sticky=('N','E','S','W'))
        #scrollbar.config(command = self.container.yview)
        # Bufferpool
        print("-- BUFFERPOOL --")
        nr = self.create_bufferpool(0,0)
        ## Tablespace
        print("-- TABLESPACES --")
        nr = self.create_tablespace(nr,0)
        ## konfigurieren der Systemuser
        print("-- SYSTEMUSERS --")
        nr = self.config_systemuser(nr,0)
        ## Switch to adm_usr
        self.switch_to_adm_usr()
        ## Anlegen der Tabellen
        print("-- TABLES --")
        nr = self.create_table(nr,0)
        ## Anlegen der Indexe
        print("-- INDEXES --")
        nr = self.create_index(0,4)
        ## Anlegen der Views
        print("-- VIEWS --")
        nr = self.create_view(0,8)
        ## Anlegen der Security-Procedure
        print("-- SECURITY PROCEDURE --")
        self.create_security_proc(nr,8)
        ## Berechtigungsvergabe für sec_usr
        print("-- GRANTS --")
        self.grant_sec_usr()
        ## Insert der Standardwerte
        print("-- DEFAULTS --")
        self.insert_defaults()
        ## fertig

    def create_bufferpool(self,row_num=0, col_num=0):
        tk.Label(self.container,text='Bufferpool',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        tk.Label(self.container,text="BPSEC04K",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = "SELECT count(*) AS cnt FROM syscat.bufferpools WHERE bpname ='BPSEC04K'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = "CREATE BUFFERPOOL BPSEC04K PAGESIZE 4 K"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        return row_num

    def create_tablespace(self,row_num=0, col_num=0):
        tk.Label(self.container,text='Tablespace',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        tk.Label(self.container,text="SECDAT04K",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = "SELECT count(*) AS cnt FROM syscat.tablespaces WHERE tbspace = 'SECDAT04K'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = "CREATE LARGE TABLESPACE SECDAT04K PAGESIZE 4 K BUFFERPOOL BPSEC04K"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        tk.Label(self.container,text="SECIDX04K",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = "SELECT count(*) AS cnt FROM syscat.tablespaces WHERE tbspace = 'SECIDX04K'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = "CREATE LARGE TABLESPACE SECIDX04K PAGESIZE 4 K BUFFERPOOL BPSEC04K"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        return row_num

    def config_systemuser(self,row_num=0, col_num=0):
        tk.Label(self.container,text='Systemuser',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        connect_user = self.con_usr.get()
        connect_user = connect_user.upper()
        admin_user = self.adm_usr.get()
        admin_user = admin_user.upper()
        secure_user = self.sec_usr.get()
        secure_user = secure_user.upper()
        row_num += 2
        tk.Label(self.container,text="Connect-User",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = f"SELECT count(*) AS cnt FROM syscat.dbauth WHERE GRANTEE = '{connect_user}' AND CONNECTAUTH ='Y'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = f"GRANT CONNECT ON DATABASE TO USER {connect_user}"
            self.create.do_it(self.ins_db2,create_sql)
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        tk.Label(self.container,text="Admin-User",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = f"SELECT count(*) AS cnt FROM syscat.dbauth WHERE GRANTEE = '{admin_user}' AND DBADMAUTH ='Y'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = f"GRANT DBADM ON DATABASE TO USER {admin_user}"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        tk.Label(self.container,text="Security-User",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = f"SELECT count(*) AS cnt FROM syscat.dbauth WHERE GRANTEE = '{secure_user}' AND SECURITYADMAUTH ='Y'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = f"GRANT SECADM ON DATABASE TO USER {secure_user}"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        #
        check_sql = f"SELECT count(*) AS cnt FROM syscat.surrogateauthids WHERE \
            TRUSTEDID = '{connect_user}' AND SURROGATEAUTHID = '{admin_user}'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = f"GRANT SETSESSIONUSER ON USER {admin_user} TO USER {connect_user}"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        check_sql = f"SELECT count(*) AS cnt FROM syscat.surrogateauthids WHERE \
            TRUSTEDID = '{connect_user}' AND SURROGATEAUTHID = '{secure_user}'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            create_sql = f"GRANT SETSESSIONUSER ON USER {secure_user} TO USER {connect_user}"
            self.create.do_it(self.ins_db2,create_sql)
            status = 0
        row_num += 2
        return row_num

    def switch_to_adm_usr(self):
        if self.con_db2 == True:
            admin_user = self.adm_usr.get()
            admin_user = admin_user.upper()
            create_sql = f"SET SESSION_USER = {admin_user}"
            self.create.do_it(self.con_db2,create_sql)

    def create_table(self,row_num=0, col_num=0):
        tk.Label(self.container,text='Table',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        obj_dict = {'T_USER':T_USER,'T_ROLE':T_ROLE,'T_SCHEMA':T_SCHEMA,'T_TABLE':T_TABLE,'T_ROUTINE':T_ROUTINE,'T_SEQUENCE':T_SEQUENCE,'T_LOG2':T_LOG2}
        for name in obj_dict.keys():
            tk.Label(self.container,text=f"{name}",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
            check_sql = f"SELECT count(*) AS cnt FROM syscat.tables WHERE tabschema = 'SEC' AND tabname = '{name}'"
            if self.check.do_it(self.ins_db2,check_sql):
                status = 1
            else:
                self.create.do_it(self.ins_db2,obj_dict[name])
                status = 0
            tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
            tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
            row_num += 2
        obj_dict = {'T_USR2ROL':T_USR2ROL,'T_SCH2ROL':T_SCH2ROL,'T_TBL2ROL':T_TBL2ROL,'T_ROU2ROL':T_ROU2ROL,'T_SEQ2ROL':T_SEQ2ROL}
        for name in obj_dict.keys():
            tk.Label(self.container,text=f"{name}",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
            check_sql = f"SELECT count(*) AS cnt FROM syscat.tables WHERE tabschema = 'SEC' AND tabname = '{name}'"
            if self.check.do_it(self.ins_db2,check_sql):
                status = 1
            else:
                self.create.do_it(self.ins_db2,obj_dict[name])
                status = 0
            tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
            tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
            row_num += 2
        return row_num

    def create_index(self,row_num=0,col_num=0):
        tk.Label(self.container,text='Index',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        obj_dict = {'X_USER':X_USER,'X_ROLE':X_ROLE,'X_SCHEMA':X_SCHEMA,'X_TABLE':X_TABLE,\
            'X_ROUTINE':X_ROUTINE,'X_SEQUENCE':X_SEQUENCE,'X_LOG2':X_LOG2}
        for name in obj_dict.keys():
            tk.Label(self.container,text=f"{name}",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
            check_sql = f"SELECT count(*) AS cnt FROM syscat.indexes WHERE indschema = 'SEC' AND indname = '{name}'"
            if self.check.do_it(self.ins_db2,check_sql):
                status = 1
            else:
                self.create.do_it(self.ins_db2,obj_dict[name])
                status = 0
            tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
            tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
            row_num += 2
        obj_dict = {'X_USR2ROL':X_USR2ROL,'X_SCH2ROL':X_SCH2ROL,'X_TBL2ROL':X_TBL2ROL,\
            'X_ROU2ROL':X_ROU2ROL,'X_SEQ2ROL':X_SEQ2ROL}
        for name in obj_dict.keys():
            tk.Label(self.container,text=f"{name}",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
            check_sql = f"SELECT count(*) AS cnt FROM syscat.indexes WHERE indschema = 'SEC' AND indname = '{name}'"
            if self.check.do_it(self.ins_db2,check_sql):
                status = 1
            else:
                self.create.do_it(self.ins_db2,obj_dict[name])
                status = 0
            tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
            tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
            row_num += 2
        obj_dict = {'X_ROLE_U':X_ROLE_U,'X_ROUTINE_U':X_ROUTINE_U,'X_SCHEMA_U':X_SCHEMA_U,'X_SEQUENCE_U':X_SEQUENCE_U,\
            'X_TABLE_U':X_TABLE_U,'X_USER_U':X_USER_U,'X_ROU2ROL_U':X_ROU2ROL_U,'X_SCH2ROL_U':X_SCH2ROL_U,'X_SEQ2ROL_U':X_SEQ2ROL_U,\
            'X_TBL2ROL_U':X_TBL2ROL_U,'X_USR2ROL_U':X_USR2ROL_U}
        for name in obj_dict.keys():
            tk.Label(self.container,text=f"{name}",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
            check_sql = f"SELECT count(*) AS cnt FROM syscat.indexes WHERE indschema = 'SEC' AND indname = '{name}'"
            if self.check.do_it(self.ins_db2,check_sql):
                status = 1
            else:
                self.create.do_it(self.ins_db2,obj_dict[name])
                status = 0
            tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
            tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
            row_num += 2
        return row_num

    def create_view(self,row_num=0,col_num=0):
        tk.Label(self.container,text='View',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        obj_dict = {'V_ROUTINEAUTH':V_ROUTINEAUTH,'V_USR2ROL':V_USR2ROL,'V_SCH2ROL':V_SCH2ROL,'V_TBL2ROL':V_TBL2ROL,'V_ROU2ROL':V_ROU2ROL,\
            'V_SEQ2ROL':V_SEQ2ROL,'V_REVOKE_USER':V_REVOKE_USER,'V_REVOKE_ROLE':V_REVOKE_ROLE,'V_REVOKE_ROLE_ACCESS':V_REVOKE_ROLE_ACCESS,\
            'V_REVOKE_TABLE_ACCESS':V_REVOKE_TABLE_ACCESS,'V_REVOKE_ROUTINE_ACCESS':V_REVOKE_ROUTINE_ACCESS,\
            'V_REVOKE_SEQUENCE_ACCESS':V_REVOKE_SEQUENCE_ACCESS,'V_GRANT_USER':V_GRANT_USER,'V_GRANT_ROLE':V_GRANT_ROLE,\
            'V_GRANT_ROLE_ACCESS':V_GRANT_ROLE_ACCESS,'V_GRANT_TABLE_ACCESS':V_GRANT_TABLE_ACCESS,'V_GRANT_ROUTINE_ACCESS':V_GRANT_ROUTINE_ACCESS,\
            'V_GRANT_SEQUENCE_ACCESS':V_GRANT_SEQUENCE_ACCESS}
        for name in obj_dict.keys():
            tk.Label(self.container,text=f"{name}",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
            check_sql = f"SELECT count(*) AS cnt FROM syscat.views WHERE viewschema = 'SEC' AND viewname = '{name}'"
            if self.check.do_it(self.ins_db2,check_sql):
                status = 1
            else:
                self.create.do_it(self.ins_db2,obj_dict[name])
                status = 0
            tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
            tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
            row_num += 2
        return row_num

    def create_security_proc(self,row_num=0,col_num=0):
        tk.Label(self.container,text='Security-Procedure',font=(22),fg='blue').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Check',font=(22),fg='blue').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text='Create',font=(22),fg='blue').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        obj_dict = {'SECURITY2':SECURITY2}
        row_num += 2
        tk.Label(self.container,text=f"SECURITY2",bg='white').grid(row=row_num,column=col_num,padx=3,pady=3,sticky=('W'))
        check_sql = f"SELECT count(*) AS cnt FROM syscat.procedures WHERE procschema = 'SEC' AND procname = 'SECURITY2'"
        if self.check.do_it(self.ins_db2,check_sql):
            status = 1
        else:
            self.create.do_it(self.ins_db2,obj_dict['SECURITY2'])
            status = 0
        tk.Label(self.container,text=self.CHECK_TXT[status],bg='white').grid(row=row_num,column=col_num+1,padx=3,pady=3,sticky=('E','W'))
        tk.Label(self.container,text=self.CREAT_TXT[status],bg='white').grid(row=row_num,column=col_num+2,padx=3,pady=3,sticky=('E','W'))
        row_num += 2
        return row_num

    def grant_sec_usr(self):
        tab_name_list:list = []
        sec_user = self.sec_usr.get()
        sec_user = sec_user.upper()
        sql = "SELECT tabname AS tabname FROM syscat.tables WHERE tabschema = 'SEC'"
        self.ins_db2.exec(sql)
        name = self.ins_db2.fetch()
        while name != False:
            tab_name_list.append(name['TABNAME'])
            name = self.ins_db2.fetch()
        for tab_name in tab_name_list:
            sql = f"GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE SEC.{tab_name} TO USER {sec_user}"
            self.ins_db2.exec(sql)
        sql = f"GRANT EXECUTE ON PROCEDURE SEC.SECURITY2 TO USER {sec_user}"
        self.ins_db2.exec(sql)

    def insert_defaults(self):
        admin_user = self.adm_usr.get()
        admin_user = admin_user.upper()
        con_user = self.con_usr.get()
        con_user = con_user.upper()
        sec_user = self.sec_usr.get()
        sec_user = sec_user.upper()
        check_sql = f"SELECT COUNT(*) AS cnt FROM sec.t_user WHERE usr_name ='{admin_user}'"
        if self.check.do_it(self.ins_db2,check_sql):
            pass
        else:
            create_sql = f"INSERT INTO SEC.T_USER (usr_id,usr_name,usr_connect,usr_start) VALUES (-1,'{admin_user}','{con_user}','1900-01-01')"
            self.create.do_it(self.ins_db2,create_sql)
        check_sql = f"SELECT COUNT(*) AS cnt FROM sec.t_user WHERE usr_name ='{sec_user}'"
        if self.check.do_it(self.ins_db2,check_sql):
            pass
        else:
            create_sql = f"INSERT INTO SEC.T_USER (usr_id,usr_name,usr_connect,usr_start) VALUES (-2,'{sec_user}','{con_user}','1900-01-01')"
            self.create.do_it(self.ins_db2,create_sql)
        check_sql = "SELECT COUNT(*) AS cnt FROM sec.t_role WHERE rol_name = 'SEC_CONNECT'"
        if self.check.do_it(self.ins_db2,check_sql):
            self.activate_default(sec_user)
        else:
            create_sql = f"INSERT INTO SEC.T_ROLE (rol_id,rol_name,rol_start) VALUES (-1,'SEC_CONNECT','1900-01-01')"
            self.create.do_it(self.ins_db2,create_sql)
            self.activate_default(sec_user)

    def activate_default(self,sec_user):
        sql = f"SET SESSION_USER = {sec_user}"
        self.con_db2.exec(sql)
        sql = f"CREATE ROLE SEC_CONNECT"
        self.con_db2.exec(sql)
        sql = f"GRANT CONNECT ON DATABASE TO ROLE SEC_CONNECT"
        self.con_db2.exec(sql)


if __name__ == '__main__':
    root = Gui()
    setup = Setup(root)
    root.mainloop()

